telegram:
  bot:
    token: 6381306175:AAHj5EIKCDZjraoz2rjnFBaqxDa4UUrr9No

server:
  port: 8080

  ssl:
    enabled: ${ssl.enabled}
    key-store: ${ssl.key.storage_path}
    key-store-password: ${ssl.key.password}
    key-store-type: PKCS12
    key-alias: tomcat

api:
  server:
    send-application-endpoint: https://api.miloverada.gov.ua/api/application
#    send-application-endpoint: http://localhost:6060/api/application
